fraud_dictionary = [
    {
        "fraud_type": "Arnaques téléphonique",
        "fraud_definition": "Concerne toutes les fraudes liées à des appels téléphoniques. Il peut s'agir d'appels silencieux ou d'appels usurpant l'identité d'une entreprise légitime ou d'appels rpomouvant des services de voyance:\n- Appels silencieux\n- Appels dans une autre langue\n- Message automatique\n- Message automatique demandant de peser sur un bouton\n- Usurpation d'identité d'entreprise légitime\n- Message mentionnant la livraison manquée d'un colis\n- Message ou appel demandant de payer des frais pour des services (livraison, indexation Google, etc.)",
        "fraud_keywords": "appel silencieux, message chinois, voyance, indexation Google, mapidea, message répondeur, sondage, bruit sonore, Amazon, Postes Canada",
        "fraud_next_steps": "- Ne pas répondre aux appels inconnus. Si c'est important, on vous laissera un message ou vous rappellera rapidement.\n- Bloquer le numéro\n- Ne pas procéder aux demandes (pser sur un bouton, effectuer un paiement, etc.)\n- Ne pas ouvrir les pièces jointes\n- Si vous avez fourni vos informations personnelles ou confidentielles lors d'un appel, contactez : \n1. Votre institution financière\n2. Les agences d’évaluation de crédit pour qu’une alerte à la fraude soit inscrite à votre dossier (Equifax Canada au numéro sans frais : 1-800-465-7166; TransUnion Canada au numéro sans frais : 1-877-525-3823à0\n3. Signalez: Centre antifraude du Canada (1 888 495-8501) et Votre service de police local"
    },
    {
        "fraud_type": "Fraude amoureuse",
        "fraud_definition": "Fraude concernant la fraude amoureuse ou relation interpersonnelle entre individu impliquant que la victime ait eu à envoyer des fonds.\n- Rencontres sur un site de rencontre ou réseaux sociaux\n- Déclaration d'affection rapide\n- Vit à l'étranger\n- Problèmes personnels (médicaux, argent, etc.)\n- Contact seulement par courriel ou messagerie instanée (Whatsapp, Telegram) ou Skype\n- Demande de fonds (virement bancaire ou achat de carte cadeaux)\n- Chantage émotionnel\n- Promesse de fonds suite à un héritage\n- Menaces de divulgation de photos intimes (sextorsion)",
        "fraud_keywords": "carte cadeau; virement; étranger; douane; skype; militaire; acteur; chanteur; Afrique; Étas-Unis; héritage; western Union",
        "fraud_next_steps": "- Signalez le compte du fraudeur sur le site de rencontre ou sur le réseau social-  Bloquez le fraudeur sur le site de rencontre, le réseau social et tout autre moyen de communication avec la personne\n- Si vous avez fourni vos informations personnelles ou confidentielles à un fraudeur, communiquez avec :\n1. Centre d’aide aux victimes d’actes criminels (CAVAC) de votre région\n2. Le Centre antifraude du Canada (1 888 495-8501) \n3. Votre institution financière\n- Les agences d’évaluation de crédit pour qu’une alerte à la fraude soit inscrite à votre dossier (Equifax Canada au numéro sans frais : 1-800-465-7166; TransUnion Canada au numéro sans frais : 1-877-525-3823)\n- Votre service de police local\n- Conservez toutes les communications que vous avez eu avec le fraudeur"
    },
    {
        "fraud_type": "Fraude fausses annonces",
        "fraud_definition": "Concerne les cas de fraude impliquant la vente ou l'achat de biens via des sites de petites annonces (Kijiji, Marketplace)\nDemande un dépôt\nDemande un montant pour la livraison\nDemande un montant pour des frais d'assurance\n",
        "fraud_keywords": "depot; virement interac; livraison; assurance",
        "fraud_next_steps": "Si vous n'avez pas effectué d'achat, envoyé des informations personnelles ou bancaires, signalez le profil du vendeur sur le site d'annonce et au Centre antifraude du Canada\n\nSi vous avez effectué un achat et envoyé des informations personnelles ou bancaires,\n- Signalez à votre service de police local\n- Signalez à votre institution financière\n- Signalez à votre agence d'évaluation de crédit pour qu'une alerte à la fraude soit inscrite à votre dossier (Equifax Canada au numéro sans frais : 1-800-465-7166; TransUnion Canada au numéro sans frais : 1-877-525-3823)"
    },
    {
        "fraud_type": "Fraude sur site de vente",
        "fraud_definition": "Concerne les cas de fraude impliquant la vente de biens en ligne, que ce soit par le biais de site web usurpant l'identité d'une entre prise légitime ou pas.\nUsurpation de l'identité d'une entreprise légitime.\n- URL du site web presque similaire au site web légitime.\n- Tous les articles sont en rabais.\n- Promotion constante sur le site web.\n- Pas d'informations de contact.\n- Adresse courriel de type \"gmail\".\n- Adresse physique ne correspondant pas à l'entreprise.\n- Piètre qualité du logo.\n- Offre de livraison gratuit.\n- Prix parfois indiqué dans une autre devise.",
        "fraud_keywords": "mauvaise qualité; non reçue; fabrication chinoise; remboursement; réponse; contact; livraison; produit québecois",
        "fraud_next_steps": "Si vous n'avez pas effectué d'achat, signalez le site web au Centre antifraude du Canada, au Bureau de la concurrence du Canada ainsi qu'à l'office de protection du consommateur\nSignalez également à l'hégergeur du site web:\n- Utiliser whatcms.org pour identifier le CMS d'un site suspect. Le site web peut être hébergé sur Shopify, GoDaddy ou autre... Si vous avez effectué des achats par carte de crédit, en plus des procédures ci-dessus:\n- Vérifiez si l'achat est annulable (bien non reçu, renseignement manquant, représentation fausse, etc.)\n- Annulez l'achat auprès du marchand: contactez le marchand par écrit pour lui annoncer l'annulation de l'achat\n- Si le marchant ne rembourse pas après 15 jours, contactez votre émetteur de carte de de crédit pour un remboursement. On vous demandera de fournir les preuves de votre achat et de vos échanges avec le marchand\n- Si vous avez des craintes, annulez votre carte de crédit et commandez-en une nouvelle\n\nSi vous avez effectué des achats par Paypal, en plus des procédures ci-dessus:\n- Vérifiez si l'achat est annulable (bien non reçu, renseignement manquant, représentation fausse, etc.)\n- Annulez l'achat auprès du marchand: contactez le marchand par écrit pour lui annoncer l'annulation de l'achat\n- Si le marchant ne rembourse pas après 15 jours, contactez Paypal pour demander un remboursement. On vous demandera de fournir les preuves de votre achat et de vos échanges avec le marchand.\n\nSi le site sur lequel vous avez fait des achats faisait de la promotion sur Facebook, \n- Rendez-vous sur la page de l'entreprise\n- Dans la section \"À propos\", cliquez sur \"Transparence de la page\"\n- Cliquez ensuite sur \"Voir tout\", puis sur \"Accéder à la page publicitaire\"\n- Sur chaque publicité, cliquez sur \"...\" puis sur \"Signaler\"\n\nSi vous avez effectué un achat et envoyé des informations personnelles ou bancaires,\n- Signalez à votre service de police local\n- Signalez à votre agence d'évaluation de crédit pour qu'une alerte à la fraude soit inscrite à votre dossier (Equifax Canada au numéro sans frais : 1-800-465-7166; TransUnion Canada au numéro sans frais : 1-877-525-3823)"
    },
    {
        "fraud_type": "Fraude à l'emploi",
        "fraud_definition": "Fraude impliquant le vol d'argent ou d'informations personnelles et bancaires par le biais d'une offre d'emploi. Les annonces sont disponibles sur des sites d'emplois réputés (Indeed, etc.), sites de petites annonces (Kijiji, etc.) et les réseaux sociaux (Marketplace, etc.). Il est également possible de recevoir des offres d'emploi par contact non sollicités par SMS et messagerie instantanée (Whatsapp, Telegram, etc.)\n\n- Travail à distance\n- Salaire hebdomadaire\n- Nombre d'heures peu élevé (15 à 20h par semaine)\n- Paiement de frais pour équipement\n- Salaire payé par chèque avec un montant plus élevé ou ne correspondant pas au salaire attendu\n- Demande d'achat de carte cadeaux\n- Tâches qui consistent à publier des publications sur les réseaux sociaux, acheter des cartes cadeaux ou \"liker\" des publications sur les réseaux sociaux\n- Offre d'investissement en cryptomonnaie\n- Paiement du salaire en cryptomonnaie",
        "fraud_keywords": "emploi; travail à distance; travail domicile; salaire hebdomaire; réminération; cryptomonnaie; tâches; carte cadeaux",
        "fraud_next_steps": "Si vous n'avez pas fourni d'information personnelle ou confidentielle, rapportez la fraude au site qui diffuse l’annonce d’emploi et rapportez la fraude au Centre antifraude du Canada.\n\nSi vous avez fourni vos informations personnelles ou confidentielles à un fraudeur, communiquez avec : \n- Votre institution financière. \n- Les agences d’évaluation de crédit pour qu’une alerte à la fraude soit inscrite à votre dossier (Equifax Canada au numéro sans frais : 1-800-465-7166; TransUnion Canada au numéro sans frais : 1-877-525-3823)\n- Signalez au  Centre antifraude du Canada (1 888 495-8501)\n- Signalez à votre service de police local\n\nSur les sites d'emploi:\n- Signalez l'annonce frauduleuse\n\nSur les réseaux sociaux:\n- Signalez le profil ainsi que l'annonce frauduleuse... Pour toute communication non sollicitées par SMS ou messagerie instanée:\n- Ne répondez pas au message, ne cliquez pas sur les liens et n'ouvrez pas les pièces jointes\n- Bloquez le numéro\n- Pour les SMS, signalez le numéro au 7726"
    },
    {
        "fraud_type": "Fraude à l'investissement",
        "fraud_definition": "- Concerne les fraudes liées à des investissement, incluant des ceux liés à la crypto. \n- Publicité pour opportunités d'investissement sur les réseaux sociaux\n- Promotion de l'opportunité par des célébrités et/ou médias réputés\n- Promesse de rendement élevés sans risque\n- Site web demandant de saisir un numéro de téléphone\n- Ouverture rapide d'un portefeuille en cryptomonnaie\n- Investissement primaire à 250$ US ou 350$ CAD\n- Appels incessants du courtier\n- Augmentation fulgurante de l'investissement\n- Demande de paiement de frais pour retirer l'argent",
        "fraud_keywords": "courtier; investisssement; Facebook; cryptomonnaie; appel; portefeuille; site web",
        "fraud_next_steps": "Si vous avez un doute sur l'opportunité d'investissement, consultez le site de l'Autorité des marchés financiers (AMF), notamment:\n- Le registre des entreprises et des individus autorisés à exercer. Il est préférable d'investir auprès des personnes inscrites auprès de l'AMF afin de s'assurer de la légitimité des entreprises et individus mais égaleement prétendre à une indemnisation en cas de fraude\n- La liste des mises en garde de l'AMF. Toutes les entreprises ou individus problématiques y sont répertoriés\n\nSi vous avez fourni vos informations personnelles ou confidentielles à un fraudeur, communiquez avec : \n- L’Autorité des marchés financiers\n- Votre institution financière.  \n- Les agences d’évaluation de crédit pour qu’une alerte à la fraude soit inscrite à votre dossier (Equifax Canada au numéro sans frais : 1-800-465-7166; TransUnion Canada au numéro sans frais : 1-877-525-3823)\n- Le Centre antifraude du Canada (1 888 495-8501)\n- Votre service de police local"
    },
    {
        "fraud_type": "Fraude aux faux prêts",
        "fraud_definition": "Fraude financière concernant les offres de prêts frauduleux. Il peut s'agir d'un courtier ou bien d'une fausse entreprise offrant des prêts \n\nOffre de prêt à taux faible\nOffre de prêt acceptée rapidement\nPas de demande de dossier de crédit\nDemande de paiement de frais divers (ouverture de dossier, assurance, etc.)",
        "fraud_keywords": "prêt; crédit; frais dossier; assurance; prêt garanti; taux faible",
        "fraud_next_steps": "Si vous n'avez pas communiqué d'informations personnelles ou bancaires, signalez au Centre antifraude du Canada\nConservez toutes les communications avec le fraudeur\nSi vous avez fourni vos informations personnelles ou confidentielles à un fraudeur, communiquez avec : \n- Votre institution financière.  \n- Les agences d’évaluation de crédit pour qu’une alerte à la fraude soit inscrite à votre dossier (Equifax Canada au numéro sans frais : 1-800-465-7166; TransUnion Canada au numéro sans frais : 1-877-525-3823) \n- Le Centre antifraude du Canada (1 888 495-8501)\n- Votre service de police local"
    },
    {
        "fraud_type": "Fraude à l'immigration",
        "fraud_definition": "Concerne les cas de fraude impliquant des services de consultants/avocats et autres personnes en position d'autorité promettant des services d'aide à l'immigration. Il peut s'agir également de tout offre d'emploi assortie d'une offre d'immigration ou d'offre de bourses pour étudiants internationaux\n\nUrsurpation de l'identité  d'Immigration, Réfugiés et Citoyenneté Canada (IRCC)\nPrétend être consultant, avocat ou représentant en immigration\nSite web faisant la promotion d'une immigration rapide au Canada\nPublicité en ligne des services d'immigration\nCourriel d'hameçonnage faisant la promotion d'offre d'emploi ou de bourses assorties d'une possibilité d'immigration\nFaux document d'immigration (formulaire, visa, etc.)\nDemande beaucoup de documents officiels (CV, acte de naissance, etc.)",
        "fraud_keywords": "vivezaucanada; centralexpress; visa; emploi; bourse; Canada; express",
        "fraud_next_steps": "Si vous n'avez fourni aucune information personnelle ou confidentielle, rapportez la fraude au Centre antifraude du Canada et téléphonez à la ligne sans frais de surveillance frontalière de l’Agence des services frontaliers du Canada au 1-888-502-9060.\n\nSi vous avez communiqué des informations personnes et si vous résidez au Canada:\n- IRCC si le fraudeur a usurpé l'identité de l'organisme\n-L’Agence des services frontaliers du Canada  (1 888-502-9060)\n-Le Centre antifraude du Canada (1 888 495-8501)\n-Votre institution financière.\n-Les agences d’évaluation de crédit pour qu’une alerte à la fraude soit inscrite à votre dossier si vouz avez déjà un dossier de crédit (Equifax Canada au numéro sans frais : 1-800-465-7166; TransUnion Canada au numéro sans frais : 1-877-525-3823) \n-Votre service de police local\n\nLes personnes habilitées à donner des conseils et représentation en immigration doivent détenir un permis et être enregistré auprès du Collège des consultants en immigration et en citoyenneté: https://college-ic.ca/protection-du-public/trouver-un-consultant-en-immigration?l=fr-CA\n\nNe pas fournir de renseignements personnels avant d'avoir vérifier la légitimité du consultant/représentant\n\nNe pas payer de frais pour un traitement plus rapide (cela n'existe pas)"
    },
    {
        "fraud_type": "Fraude au logement - annonces frauduleuses",
        "fraud_definition": "Concerne toutes les fraudes liées aux annonces frauduleuses de logements à louer\nSur les sites de petites annonces et Facebook Marketplace\nContact avec l'annonceur seulement par courriel ou messagerie instantanée\nDescription du logement très détaillé\nImpossibilité de rencontrer l'annonceur pour la visite\nDemande d'informations personnelles par courriel\nDemande de paiement d'un dépôt\n2 ou 3 photos du logement",
        "fraud_keywords": "logement; tout inclus; disponibilité;  conditions; whatsapp; BTC; dépôt; bail; premier mois; cryptomonnaie",
        "fraud_next_steps": "Sites petites annonces: Contacter les responsables du site qui héberge l'annonce \nMarketplace: signaler l'annonce et le profil\nSignaler au Centre anti-fraude du Canada\nSi vous avez fourni des renseignements personnels et/ou bancaires:\n- Signalez à votre service de police local\n- Signalez à votre institution financière\n- Signalez à votre agence d'évaluation de crédit pour qu'une alerte à la fraude soit inscrite à votre dossier (Equifax Canada au numéro sans frais : 1-800-465-7166; TransUnion Canada au numéro sans frais : 1-877-525-3823)\n"
    },
    {
        "fraud_type": "Fraude au logement - courriel loyers impayés",
        "fraud_definition": "Concerne les courriels d'hameçonnage prétextant la demande de paiement d'un loyer impayé",
        "fraud_keywords": "loyer impayé; interac; règlement; situation; rapidement; gestion locative; gestion immo",
        "fraud_next_steps": "Contacter votre propriétaire pour vous assurer de la provenance du courriel\nSignaler le courriel comme pourriel\nSupprimer le courriel\nNe pas ouvrir la pièce jointe\nNe pas envoyer d'argent"
    },
    {
        "fraud_type": "Hameçonnage par courriel",
        "fraud_definition": "Le courriel se présente comme provenant d'utilisateurs ou d'organisations légitimes dont objectif est d'obtenir un accès illégitime aux comptes de leurs victimes afin de voler des données personnelles ou financières.\n\nCourriels usurpant l'identité d’entreprises connues, d'agence gouvernementales ou services utilitaires.\nUtilisation d'un langage suscitant l'urgence\nDemande de paiement\nOffre de remboursement\nPrésence d'un lien dirigeant vers un site web frauduleux\nDemande de mise  jour d'informations\nMenaces de divulgation d'informations personnelles\nFaux logo",
        "fraud_keywords": "courriel; impôt; revenu Canada; Amazon; abonnement; microsoft; outlook; antivirus; concours; loterie; Fedex; UPS",
        "fraud_next_steps": "Signaler le courriel comme étant pourriel\nSupprimer le courriel\nNe pas cliquer sur les liens\nNe pas ouvrir les pièces jointes"
    },
    {
        "fraud_type": "Hameçonnage SMS",
        "fraud_definition": "Le SMS se présente comme provenant d'utilisateurs ou d'organisations légitimes dont objectif est d'obtenir un accès illégitime aux comptes de leurs victimes afin de voler des données personnelles ou financières.\nSMS usurpant l'identité d’entreprises connues, d'agence gouvernementales ou services utilitaires\nUtilisation d'un langage suscitant l'urgence\nDemande de paiement\nOffre de remboursement\nPrésence d'un lien raccourci dirigeant vers un site web frauduleux\nDemande de mise  jour d'informations",
        "fraud_keywords": "SMS; message texte; texto; impôt; poste canada; Amazon;  Fedex; UPS; remboursement; gigadat; interac; sationnement; excès de vitesse; hydro québec",
        "fraud_next_steps": "Signaler le message texte au 7726\nSupprimer le message\nNe pas cliquer sur les liens"
    }
]

fraud_d =  {
        "fraud_type": "Arnaques téléphonique",
        "fraud_definition": "Concerne toutes les fraudes liées à des appels téléphoniques. Il peut s'agir d'appels silencieux ou d'appels usurpant l'identité d'une entreprise légitime ou d'appels rpomouvant des services de voyance:\n- Appels silencieux\n- Appels dans une autre langue\n- Message automatique\n- Message automatique demandant de peser sur un bouton\n- Usurpation d'identité d'entreprise légitime\n- Message mentionnant la livraison manquée d'un colis\n- Message ou appel demandant de payer des frais pour des services (livraison, indexation Google, etc.)",
        "fraud_keywords": "appel silencieux, message chinois, voyance, indexation Google, mapidea, message répondeur, sondage, bruit sonore, Amazon, Postes Canada",
        "fraud_next_steps": "- Ne pas répondre aux appels inconnus. Si c'est important, on vous laissera un message ou vous rappellera rapidement.\n- Bloquer le numéro\n- Ne pas procéder aux demandes (pser sur un bouton, effectuer un paiement, etc.)\n- Ne pas ouvrir les pièces jointes\n- Si vous avez fourni vos informations personnelles ou confidentielles lors d'un appel, contactez : \n1. Votre institution financière\n2. Les agences d’évaluation de crédit pour qu’une alerte à la fraude soit inscrite à votre dossier (Equifax Canada au numéro sans frais : 1-800-465-7166; TransUnion Canada au numéro sans frais : 1-877-525-3823à0\n3. Signalez: Centre antifraude du Canada (1 888 495-8501) et Votre service de police local"
    }